### ISSUE TITLE
sendMessageToPeerV2 function does not return error code or error description for ios

### ISSUE THREAD

**Issue by louxinbo** [AgoraIO/agora-react-native-rtm#54]
I'm using `sendMessageToPeerV2` to send message and when there's an Error, I'll make the message a failed message to let users to resend.
There's an issue that, the offline message (I enabled this) will also trigger an error (I saw the error code from Android app, it's `Error: PEER_MESSAGE_ERR_CACHED_BY_SERVER`)

It's fine, I can exclude this if I know the error type, but the issue is when it comes to ios, it does not give any error code or error description. It only returns `Error`. It means every offline message will become failed message.

Anyone has a good workaround? Thanks.

**Comment by LichKing-2234** [comment]
Fixed by https://github.com/AgoraIO/agora-react-native-rtm/pull/56

**Comment by LichKing-2234** [comment]
You can try this
https://github.com/AgoraIO/agora-react-native-rtm/pull/56

**Comment by louxinbo** [comment]
@zhigang1992 @LichKing-2234 
Thanks for the update, but I still have the same issue. 
There's no detail in the error code. Here's the error I got from the ios app (has upgraded to version 1.4.9):
```
Error
    at Object.promiseMethodWrapper [as sendMessageToPeer] (VM4 index.bundle:3275)
    at RtmEngine.sendMessageToPeerV2 (VM4 index.bundle:211876)
    at _callee2$ (VM4 index.bundle:286192)
    at tryCatch (VM4 index.bundle:1464)
    at Generator.invoke [as _invoke] (VM4 index.bundle:1634)
    at Generator.next (VM4 index.bundle:1506)
    at tryCatch (VM4 index.bundle:1464)
    at invoke (VM4 index.bundle:1536)
    at VM4 index.bundle:1566
    at tryCallTwo (VM4 index.bundle:31209)
```
Here's the error I can get from Android app:
```
Error: PEER_MESSAGE_ERR_CACHED_BY_SERVER
    at Object.promiseMethodWrapper [as sendMessageToPeer] (C:\MyWork\andi-health-passport\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:104)
    at RtmEngine.sendMessageToPeerV2 (C:\MyWork\andi-health-passport\node_modules\agora-react-native-rtm\src\RtmEngine.ts:531)
    at _callee2$ (C:\MyWork\andi-health-passport\screens\Chat\ChatScreen.js:177)
    at tryCatch (C:\MyWork\andi-health-passport\node_modules\regenerator-runtime\runtime.js:63)
    at Generator.invoke [as _invoke] (C:\MyWork\andi-health-passport\node_modules\regenerator-runtime\runtime.js:294)
    at Generator.next (C:\MyWork\andi-health-passport\node_modules\regenerator-runtime\runtime.js:119)
    at tryCatch (C:\MyWork\andi-health-passport\node_modules\regenerator-runtime\runtime.js:63)
    at invoke (C:\MyWork\andi-health-passport\node_modules\regenerator-runtime\runtime.js:155)
    at C:\MyWork\andi-health-passport\node_modules\regenerator-runtime\runtime.js:165
    at tryCallOne (C:\MyWork\andi-health-passport\node_modules\promise\setimmediate\core.js:37)
```

**Comment by louxinbo** [comment]
@zhigang1992 @LichKing-2234 
Thanks for your help. I found that though `error.message` is blank, `error.code` is valid. Now i can use `error.code ==4` to check if a message is a failed one or a offline one.
